# NumPy Basics

NumPy (Numerical Python) is the foundation of scientific computing in Python.

It provides fast numerical operations using arrays instead of Python lists.

Why important for AI?<br>
Machine learning models operate on matrices and vectors — not loops.

In [1]:
import numpy as np

## Python List vs NumPy Array

Python lists store references → slower for math  
NumPy arrays store contiguous memory → faster operations

In [2]:
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

print(type(python_list))
print(type(numpy_array))

<class 'list'>
<class 'numpy.ndarray'>


## Creating NumPy Arrays
Arrays can be created from lists or built-in functions

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


## Built-in Array Creators

In [4]:
print(np.zeros(5))
print(np.ones((2,3)))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Array Properties
Useful attributes to understand data structure

In [6]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


## Summary

We learned:
- NumPy arrays vs Python lists
- Creating arrays
- Built-in creators
- Array properties

This forms the base for numerical computing in machine learning.