# Array Operations

In machine learning, data rarely comes in the correct shape.

We often need to reshape, convert, and manage memory efficiently.

In [1]:
import numpy as np

## Reshaping Arrays

Reshape changes dimensions without changing data.

In [2]:
arr = np.arange(1, 13)
print(arr)

reshaped = arr.reshape(3,4)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Flattening Arrays

Convert multi-dimensional array → 1D array

In [3]:
flat = reshaped.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## NumPy Data Types

NumPy supports efficient numeric types

In [4]:
arr = np.array([1,2,3], dtype=np.int32)
print(arr.dtype)

int32


## astype()

Convert array data type

In [5]:
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

[1. 2. 3.]
float64


## Copy vs View

View → shares memory  
Copy → new memory

In [6]:
a = np.array([1,2,3,4])
b = a.view()

b[0] = 99

print("a:", a)
print("b:", b)

a: [99  2  3  4]
b: [99  2  3  4]


In [7]:
c = a.copy()
c[1] = 100

print("a:", a)
print("c:", c)

a: [99  2  3  4]
c: [ 99 100   3   4]


## Summary

We learned:
- reshape
- flatten
- dtype & astype
- copy vs view

These are critical for data preprocessing in ML.