# Indexing & Slicing in NumPy

Selecting specific data is essential in Machine Learning.

We often extract rows, columns, and filtered values from datasets.

In [1]:
import numpy as np

## Basic Indexing
Access individual elements

In [2]:
arr = np.array([10,20,30,40,50])

print(arr[0])     # first element
print(arr[-1])    # last element

10
50


## 2D Indexing
Access rows and columns

In [3]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix[0,1])  # row 0 col 1
print(matrix[2,2])  # last element

2
9


## Slicing Arrays
Extract ranges of data

In [4]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])     # 20 30 40
print(arr[:3])      # first three
print(arr[::2])     # step slicing

[20 30 40]
[10 20 30]
[10 30 50]


In [5]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix[:,1])   # second column
print(matrix[1,:])   # second row

[2 5 8]
[4 5 6]


## Boolean Indexing
Filter elements based on condition

In [ ]:
arr = np.array([5,12,7,18,3,20])

# select elements greater than 10
filtered = arr[arr > 10]
print(filtered)

[12 18 20]


## Fancy Indexing
Select elements using index list

In [7]:
arr = np.array([10,20,30,40,50])

print(arr[[0,2,4]])  # select positions

[10 30 50]


## Summary

We learned:
- indexing
- slicing
- boolean filtering
- fancy indexing

These are heavily used in dataset preprocessing.