# Multidimensional Arrays

Machine learning datasets are tables:<br>
rows → data samples<br>
columns → features

NumPy handles multi-dimensional arrays efficiently.

In [1]:
import numpy as np

## 2D Arrays (Matrix)

In [2]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2


## Accessing Rows and Columns

In [3]:
# first row
print(matrix[0])

# second column
print(matrix[:,1])

[1 2 3]
[2 5 8]


## 3D Arrays

Used in images, videos, and deep learning tensors

In [4]:
tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor)
print("Shape:", tensor.shape)
print("Dimensions:", tensor.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


## Axis Concept

Axis 0 → rows (downwards)<br>
Axis 1 → columns (across)<br>
Axis 2 → depth (3D)

In [5]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Sum axis 0 (column wise):", np.sum(matrix, axis=0))
print("Sum axis 1 (row wise):", np.sum(matrix, axis=1))

Sum axis 0 (column wise): [12 15 18]
Sum axis 1 (row wise): [ 6 15 24]


In [6]:
# mean of each feature(column)
print("Column mean:", np.mean(matrix, axis=0))

Column mean: [4. 5. 6.]


## Summary

We learned:
- 2D & 3D arrays
- rows vs columns
- axis operations

This is the base of dataset processing in ML.