# Vectorization & Broadcasting

NumPy allows operations on entire arrays without loops.

This is called vectorization and is critical for fast machine learning computations.

In [1]:
import numpy as np

## Vectorized Operations

Operations apply element-wise automatically

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a + b)

[11 22 33 44]


In [3]:
print(a * 2)
print(a ** 2)

[2 4 6 8]
[ 1  4  9 16]


Vectorization is faster than Python loops because NumPy runs in optimized C code.

## Broadcasting

Allows operations between arrays of different shapes

In [4]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

vector = np.array([10,20,30])

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


Rules:
1. Dimensions must match OR
2. One of them must be 1

In [5]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Vector Normalization

Used in ML to scale features

In [6]:
vec = np.array([3,4])

norm = np.sqrt(np.sum(vec**2))
normalized = vec / norm

print("Normalized vector:", normalized)

Normalized vector: [0.6 0.8]


## Summary

We learned:
- vector operations
- broadcasting
- normalization

This is essential for machine learning performance.