# 🧠 Building a Neuron with PyTorch

In this notebook we will build a **single artificial neuron using PyTorch**.

A neuron performs three main steps:

1️⃣ Multiply inputs with weights  
2️⃣ Add a bias  
3️⃣ Produce an output

Mathematically:
```
z = w₁x₁ + w₂x₂ + w₃x₃ + b
```
PyTorch provides a built-in layer called:

nn.Linear()

which represents a **fully connected neuron**.

## ⚙️ Step 1: Import Libraries

We first import **PyTorch** and its neural network module.

In [8]:
import torch
import torch.nn as nn

## 📥 Step 2: Create Input Tensor

We create a tensor representing **three input features**.

Example inputs:
- x₁
- x₂
- x₃

In [9]:
# Set seed for reproducibility
torch.manual_seed(42)

# Input tensor
inputs = torch.tensor([1.0, 2.0, 3.0])

## 🧠 Step 3: Create a Neuron

We create a neuron using:

nn.Linear(in_features, out_features)

Parameters:

in_features → number of inputs  
out_features → number of neurons

Since we are building **one neuron**, the output size is 1.

In [10]:
# Create a single neuron
neuron = nn.Linear(in_features=3, out_features=1)

## 🚀 Step 4: Forward Pass

Now we pass the inputs through the neuron.

This performs:
```
z = w₁x₁ + w₂x₂ + w₃x₃ + b
```

In [11]:
output = neuron(inputs)

print("Neuron Output:", output)

Neuron Output: tensor([1.5244], grad_fn=<ViewBackward0>)


## 🔍 Step 5: Verify the Formula Manually

We verify that PyTorch computes the same result using:
```
z = w · x + b
```

In [12]:
# Manual computation
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

## ⚙️ Step 6: Inspect Weights

In [13]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

## ⚙️ Step 7: Inspect Bias

In [14]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

## 📊 Summary

In this notebook we learned:

✔ A neuron performs a weighted sum of inputs  
✔ PyTorch provides `nn.Linear()` to represent a neuron  
✔ The neuron internally calculates:

z = w₁x₁ + w₂x₂ + w₃x₃ + b

This simple neuron is the **basic building block of neural networks**.

Multiple neurons combined together form **deep neural networks**.